version: "3.9"
services:
  api:
    container_name: api_skystar
    build: ./api
    links:
      - db
    ports:
      - ${API_PORT_LOCAL}:8000
    volumes:
      - /app/var
      - /app/vendor
      - ./api/dev:/app
  # db:
  #   container_name: db_skystar
  #   build: ./db
  #   restart: always
  #   expose:
  #     - "3306"
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./db/data:/var/lib/mysql
  #   environment:
  #     MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
  #     MARIADB_ROOT_HOST: "%"
  db:
    build: ./db
    restart: always
    ports:
      - ${DB_PORT_LOCAL}:5432
    environment:
      POSTGRES_DB: skystar
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pswd
  adminer:
    image: adminer
    restart: always
    links:
      - db
    ports:
      - ${ADMINER_PORT_LOCAL}:8080
    environment:
      - ADMINER_DESIGN=pepa-linha
  app:
    build: ./app
    expose:
      - 4200
    ports:
      - ${APP_PORT_LOCAL}:4200
    volumes:
      - /app/.angular
      - /app/node_modules
      - ./app/dev:/app
