version: "3.9"
services:
  api:
    container_name: api_skystar
    build: ./api
    depends_on:
      - db
    ports:
      - ${API_PORT_LOCAL}:8000
    volumes:
      - /app/var
      - /app/vendor
      - ./api/dev:/app
  # # Décommenter pour démarrer le service
  # # Ce service est une instance de python avec les bons requirements pour utiliser le script qui génère la base de donnée
  # python-db-script:
  #   build: ./python-db-script
  #   depends_on:
  #     - db
  #   tty: true
  #   environment:
  #     - DB_USER=user
  #     - DB_PASSWORD=pswd
  #     - DB_DATABASE=skystar
  db:
    build: ./db
    restart: always
    ports:
      - ${DB_PORT_LOCAL}:5432
    environment:
      POSTGRES_DB: skystar
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pswd
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - ${ADMINER_PORT_LOCAL}:8080
    environment:
      - ADMINER_DESIGN=mvt
  app:
    build: ./app
    expose:
      - 4200
    ports:
      - ${APP_PORT_LOCAL}:4200
    volumes:
      - /app/.angular
      - /app/node_modules
      - ./app/dev:/app
    environment:
      - API_PORT_LOCAL=${API_PORT_LOCAL}
    tty: true
