version: "3.9"
services:
  db:
    container_name: db_projet_it_L3
    build: ./db
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: db_projet_it_L3
      MARIADB_ROOT_HOST: "%"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
