-- SQLINES DEMO *** sktop version to convert large SQL scripts,
-- SQLINES DEMO *** ny issues with Online conversion.

-- SQLINES DEMO *** act us at support@sqlines.com

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE SEQUENCE CONSTELLATION_seq;

CREATE TABLE IF NOT EXISTS CONSTELLATION
(
ID_CONSTELLATION INTEGER NOT NULL DEFAULT NEXTVAL ('CONSTELLATION_seq') ,
LATIN_NAME CHAR(50) NULL ,
OBSERVATION_SAISON CHAR(100) NULL ,
ETOILE_PRINCIPALE CHAR(40) NULL ,
RA DECIMAL(10,5) NULL ,
DECA DECIMAL(10,5) NULL ,
TAILLE DECIMAL(15,5) NULL ,
CREATED TIMESTAMP NULL ,
UPDATED TIMESTAMP NULL
, PRIMARY KEY (ID_CONSTELLATION)
);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE SEQUENCE JEU_seq;

CREATE TABLE IF NOT EXISTS JEU
(
ID_JEU INTEGER NOT NULL DEFAULT NEXTVAL ('JEU_seq'),
ID_CONSTELLATION INTEGER NULL ,
ID_OBJET_DISTANT INTEGER NULL ,
PSEUDO CHAR(20) NULL ,
TROUVER SMALLINT NULL ,
DUREE TIMESTAMP NULL ,
DATE_CREATION TIMESTAMP NULL ,
CREATED TIMESTAMP NULL ,
UPDATED TIMESTAMP NULL
, PRIMARY KEY (ID_JEU)
);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE INDEX I_FK_JEU_CONSTELLATION
ON JEU (ID_CONSTELLATION ASC);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE INDEX I_FK_JEU_OBJET_DISTANT
ON JEU (ID_OBJET_DISTANT ASC);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE SEQUENCE OBJET_DISTANT_seq;

CREATE TABLE IF NOT EXISTS OBJET_DISTANT
(
ID_OBJET_DISTANT INTEGER NOT NULL DEFAULT NEXTVAL ('OBJET_DISTANT_seq') ,
RA DECIMAL(10,5) NULL ,
DECA DECIMAL(10,5) NULL ,
MAGNITUDE DECIMAL(10,3) NULL ,
RA_RADIANS DECIMAL(10,5) NULL ,
DEC_RADIANS DECIMAL(10,5) NULL ,
TYPE CHAR(50) NULL ,
CREATED TIMESTAMP NULL ,
UPDATED TIMESTAMP NULL
, PRIMARY KEY (ID_OBJET_DISTANT)
);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE SEQUENCE OBJET_PROCHE_seq;

CREATE TABLE IF NOT EXISTS OBJET_PROCHE
(
ID_OBJET_PROCHE INTEGER NOT NULL DEFAULT NEXTVAL ('OBJET_PROCHE_seq') ,
NOM CHAR(32) NULL ,
MAGNITUDE DECIMAL(10,5) NULL ,
RA DECIMAL(10,5) NULL ,
DECA DECIMAL(10,5) NULL ,
TYPE CHAR(32) NULL ,
DATE_APPROBATION CHAR(32) NULL
, PRIMARY KEY (ID_OBJET_PROCHE)
);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE SEQUENCE PARCOURS_seq;

CREATE TABLE IF NOT EXISTS PARCOURS
(
ID_PARCOURS INTEGER NOT NULL DEFAULT NEXTVAL ('PARCOURS_seq') ,
ID_JEU INTEGER NOT NULL ,
RA DECIMAL(10,5) NULL ,
DECA DECIMAL(10,5) NULL ,
MAGNITUDE DECIMAL(10,5) NULL ,
CREATED TIMESTAMP NULL ,
UPDATED TIMESTAMP NULL
, PRIMARY KEY (ID_PARCOURS)
);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE INDEX I_FK_PARCOURS_JEU
ON PARCOURS (ID_JEU ASC);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE SEQUENCE GROUPER_seq;

CREATE TABLE IF NOT EXISTS GROUPER
(
ID_OBJET_DISTANT INTEGER NOT NULL DEFAULT NEXTVAL ('GROUPER_seq') ,
ID_CONSTELLATION INTEGER NOT NULL
, PRIMARY KEY (ID_OBJET_DISTANT,ID_CONSTELLATION)
);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE INDEX I_FK_GROUPER_OBJET_DISTANT
ON GROUPER (ID_OBJET_DISTANT ASC);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE INDEX I_FK_GROUPER_CONSTELLATION
ON GROUPER (ID_CONSTELLATION ASC);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE SEQUENCE DETERMINER_seq;

CREATE TABLE IF NOT EXISTS DETERMINER
(
ID_OBJET_PROCHE INTEGER NOT NULL DEFAULT NEXTVAL ('DETERMINER_seq') ,
ID_CONSTELLATION INTEGER NOT NULL
, PRIMARY KEY (ID_OBJET_PROCHE,ID_CONSTELLATION)
);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE INDEX I_FK_DETERMINER_OBJET_PROCHE
ON DETERMINER (ID_OBJET_PROCHE ASC);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE INDEX I_FK_DETERMINER_CONSTELLATION
ON DETERMINER (ID_CONSTELLATION ASC);
ALTER TABLE JEU
ADD CONSTRAINT FK_JEU_CONSTELLATION FOREIGN KEY (ID_CONSTELLATION)
REFERENCES CONSTELLATION (ID_CONSTELLATION) ;
ALTER TABLE JEU
ADD CONSTRAINT FK_JEU_OBJET_DISTANT FOREIGN KEY (ID_OBJET_DISTANT)
REFERENCES OBJET_DISTANT (ID_OBJET_DISTANT) ;
ALTER TABLE PARCOURS
ADD CONSTRAINT FK_PARCOURS_JEU FOREIGN KEY (ID_JEU)
REFERENCES JEU (ID_JEU) ;
ALTER TABLE GROUPER
ADD CONSTRAINT FK_GROUPER_OBJET_DISTANT FOREIGN KEY (ID_OBJET_DISTANT)
REFERENCES OBJET_DISTANT (ID_OBJET_DISTANT) ;
ALTER TABLE GROUPER
ADD CONSTRAINT FK_GROUPER_CONSTELLATION FOREIGN KEY (ID_CONSTELLATION)
REFERENCES CONSTELLATION (ID_CONSTELLATION) ;
ALTER TABLE DETERMINER
ADD CONSTRAINT FK_DETERMINER_OBJET_PROCHE FOREIGN KEY (ID_OBJET_PROCHE)
REFERENCES OBJET_PROCHE (ID_OBJET_PROCHE) ;
ALTER TABLE DETERMINER 
ADD CONSTRAINT FK_DETERMINER_CONSTELLATION FOREIGN KEY (ID_CONSTELLATION)
REFERENCES CONSTELLATION (ID_CONSTELLATION) ;