DROP DATABASE IF EXISTS skystar;

CREATE DATABASE IF NOT EXISTS skystar;
USE skystar;

CREATE TABLE IF NOT EXISTS CONSTELLATION
 (
   ID_CONSTELLATION INTEGER(8) NOT NULL AUTO_INCREMENT  ,
   LATIN_NAME CHAR(50) NULL  ,
   OBSERVATION_SAISON CHAR(100) NULL  ,
   ETOILE_PRINCIPALE CHAR(40) NULL  ,
   RA DECIMAL(10,5) NULL  ,
   DECA DECIMAL(10,5) NULL  ,
   TAILLE DECIMAL(15,5) NULL  ,
   CREATED DATETIME NULL  ,
   UPDATED DATETIME NULL  
   , PRIMARY KEY (ID_CONSTELLATION) 
 ) 
 comment = "";

CREATE TABLE IF NOT EXISTS JEU
 (
   ID_JEU INTEGER(5) NOT NULL  AUTO_INCREMENT,
   ID_CONSTELLATION INTEGER(8) NULL  ,
   ID_OBJET_DISTANT INTEGER(5) NULL  ,
   PSEUDO CHAR(20) NULL  ,
   TROUVER TINYINT(1) NULL  ,
   DUREE DATETIME NULL  ,
   DATE_CREATION DATETIME NULL  ,
   CREATED DATETIME NULL  ,
   UPDATED DATETIME NULL  
   , PRIMARY KEY (ID_JEU) 
 ) 
 comment = "";

CREATE  INDEX I_FK_JEU_CONSTELLATION
     ON JEU (ID_CONSTELLATION ASC);

CREATE  INDEX I_FK_JEU_OBJET_DISTANT
     ON JEU (ID_OBJET_DISTANT ASC);

CREATE TABLE IF NOT EXISTS OBJET_DISTANT
 (
   ID_OBJET_DISTANT INTEGER(5) NOT NULL AUTO_INCREMENT ,
   RA DECIMAL(10,5) NULL  ,
   DECA DECIMAL(10,5) NULL  ,
   MAGNITUDE REAL(10,3) NULL  ,
   RA_RADIANS REAL(10,5) NULL  ,
   DEC_RADIANS REAL(10,5) NULL  ,
   TYPE CHAR(50) NULL  ,
   CREATED DATETIME NULL  ,
   UPDATED DATETIME NULL  
   , PRIMARY KEY (ID_OBJET_DISTANT) 
 ) 
 comment = "";

CREATE TABLE IF NOT EXISTS OBJET_PROCHE
 (
   ID_OBJET_PROCHE INTEGER(5) NOT NULL AUTO_INCREMENT ,
   NOM CHAR(32) NULL  ,
   MAGNITUDE REAL(10,5) NULL  ,
   RA DECIMAL(10,5) NULL  ,
   DECA DECIMAL(10,5) NULL  ,
   TYPE CHAR(32) NULL  ,
   DATE_APPROBATION CHAR(32) NULL  
   , PRIMARY KEY (ID_OBJET_PROCHE) 
 ) 
 comment = "";

CREATE TABLE IF NOT EXISTS PARCOURS
 (
   ID_PARCOURS INTEGER(5) NOT NULL AUTO_INCREMENT  ,
   ID_JEU INTEGER(5) NOT NULL  ,
   RA DECIMAL(10,5) NULL  ,
   DECA DECIMAL(10,5) NULL  ,
   MAGNITUDE REAL(10,5) NULL  ,
   CREATED DATETIME NULL  ,
   UPDATED DATETIME NULL  
   , PRIMARY KEY (ID_PARCOURS) 
 ) 
 comment = "";

CREATE  INDEX I_FK_PARCOURS_JEU
     ON PARCOURS (ID_JEU ASC);

CREATE TABLE IF NOT EXISTS GROUPER
 (
   ID_OBJET_DISTANT INTEGER(5) NOT NULL AUTO_INCREMENT  ,
   ID_CONSTELLATION INTEGER(8) NOT NULL  
   , PRIMARY KEY (ID_OBJET_DISTANT,ID_CONSTELLATION) 
 ) 
 comment = "";

CREATE  INDEX I_FK_GROUPER_OBJET_DISTANT
     ON GROUPER (ID_OBJET_DISTANT ASC);

CREATE  INDEX I_FK_GROUPER_CONSTELLATION
     ON GROUPER (ID_CONSTELLATION ASC);

CREATE TABLE IF NOT EXISTS DETERMINER
 (
   ID_OBJET_PROCHE INTEGER(5) NOT NULL AUTO_INCREMENT ,
   ID_CONSTELLATION INTEGER(8) NOT NULL  
   , PRIMARY KEY (ID_OBJET_PROCHE,ID_CONSTELLATION) 
 ) 
 comment = "";

CREATE  INDEX I_FK_DETERMINER_OBJET_PROCHE
     ON DETERMINER (ID_OBJET_PROCHE ASC);

CREATE  INDEX I_FK_DETERMINER_CONSTELLATION
     ON DETERMINER (ID_CONSTELLATION ASC);

ALTER TABLE JEU 
  ADD FOREIGN KEY FK_JEU_CONSTELLATION (ID_CONSTELLATION)
      REFERENCES CONSTELLATION (ID_CONSTELLATION) ;


ALTER TABLE JEU 
  ADD FOREIGN KEY FK_JEU_OBJET_DISTANT (ID_OBJET_DISTANT)
      REFERENCES OBJET_DISTANT (ID_OBJET_DISTANT) ;


ALTER TABLE PARCOURS 
  ADD FOREIGN KEY FK_PARCOURS_JEU (ID_JEU)
      REFERENCES JEU (ID_JEU) ;


ALTER TABLE GROUPER 
  ADD FOREIGN KEY FK_GROUPER_OBJET_DISTANT (ID_OBJET_DISTANT)
      REFERENCES OBJET_DISTANT (ID_OBJET_DISTANT) ;


ALTER TABLE GROUPER 
  ADD FOREIGN KEY FK_GROUPER_CONSTELLATION (ID_CONSTELLATION)
      REFERENCES CONSTELLATION (ID_CONSTELLATION) ;


ALTER TABLE DETERMINER 
  ADD FOREIGN KEY FK_DETERMINER_OBJET_PROCHE (ID_OBJET_PROCHE)
      REFERENCES OBJET_PROCHE (ID_OBJET_PROCHE) ;


ALTER TABLE DETERMINER 
  ADD FOREIGN KEY FK_DETERMINER_CONSTELLATION (ID_CONSTELLATION)
      REFERENCES CONSTELLATION (ID_CONSTELLATION) ;

